[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd src && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --worker-class gthread"
